[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
