[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_SKEW_PROTECTION = "true"

[dev]
  command = "netlify dev"
